### ISSUE TITLE
请给一个 pvc的示例

### ISSUE THREAD

**Issue by aland-zhang** [tennix/k8s-lvm-manager#1]
根据demo 中的示例 
```
volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: lvm-volume-provisioner
      resources:
        requests:
          storage: 30M

lvm-provisioner pod 里面报错 
Operation for "provision-default/test[7fffeb88-feaf-11e8-889e-525400614a73]" failed. No retries permitted until 2018-12-13 16:36:23.623208633 +0800 CST m=+1592.341151790 (durationBeforeRetry 2m2s). Error: "pvc doesn't contain nodeName annotation"

**rovisioning Failed | Failed to provision volume with StorageClass "lvm-volume-provisioner": pvc doesn't contain nodeName annotation**

```
更给一个完整的pvc例子么？ 谢谢
